### ISSUE TITLE
unable to push slack-type-inviter to heroku

### ISSUE THREAD

**Issue by bdougie** [icodeforlove/slack-typeform-inviter#3]
Having this issue issues trying to push an app with this package included. I added the `/node_modules` to the `.gitignore` file, so the `npm install` is happening on deploy. 

Not understanding why the Cubby package is not being found, does it have anything to do with the variable being `Cubby` and not `cubby` in the `?

Is there a better way to push this to a persistent web server? Maybe another service.

``` javascript
// This is the heroku logs console
Brian-Douglas-MacBook-Pro:invite_machine briandouglas$ heroku logs
2015-02-04T09:38:44.276512+00:00 app[web.1]:     at Module.load (module.js:355:32)
2015-02-04T09:38:45.072717+00:00 heroku[web.1]: Process exited with status 1
2015-02-04T09:38:45.087536+00:00 heroku[web.1]: State changed from starting to crashed
2015-02-05T04:59:27.037182+00:00 heroku[web.1]: State changed from crashed to starting
2015-02-05T04:59:29.924302+00:00 heroku[web.1]: Starting process with command `node --harmony index.js`
2015-02-05T04:59:33.761653+00:00 app[web.1]:     throw err;
2015-02-05T04:59:33.761656+00:00 app[web.1]:           ^
2015-02-05T04:59:33.761657+00:00 app[web.1]: Error: Cannot find module 'Cubby'
2015-02-05T04:59:33.761659+00:00 app[web.1]:     at Function.Module._resolveFilename (module.js:336:15)
2015-02-05T04:59:33.761661+00:00 app[web.1]:     at Function.Module._load (module.js:278:25)
2015-02-05T04:59:33.761662+00:00 app[web.1]:     at Module.require (module.js:365:17)
2015-02-05T04:59:33.761633+00:00 app[web.1]: module.js:338
2015-02-05T04:59:33.761666+00:00 app[web.1]:     at Object.<anonymous> (/app/node_modules/slack-typeform-inviter/lib/SlackAutoInviter.js:5:10)
2015-02-05T04:59:33.761667+00:00 app[web.1]:     at Module._compile (module.js:460:26)
2015-02-05T04:59:33.761663+00:00 app[web.1]:     at require (module.js:384:17)
2015-02-05T04:59:33.761669+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:478:10)
2015-02-05T04:59:33.761673+00:00 app[web.1]:     at Function.Module._load (module.js:310:12)
2015-02-05T04:59:33.761677+00:00 app[web.1]:     at require (module.js:384:17)
2015-02-05T04:59:33.761680+00:00 app[web.1]:     at Module._compile (module.js:460:26)
2015-02-05T04:59:33.761678+00:00 app[web.1]:     at Object.<anonymous> (/app/node_modules/slack-typeform-inviter/index.js:1:80)
2015-02-05T04:59:33.761672+00:00 app[web.1]:     at Module.load (module.js:355:32)
2015-02-05T04:59:33.761675+00:00 app[web.1]:     at Module.require (module.js:365:17)
2015-02-05T04:59:33.761684+00:00 app[web.1]:     at Function.Module._load (module.js:310:12)
2015-02-05T04:59:33.761681+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:478:10)
2015-02-05T04:59:33.761683+00:00 app[web.1]:     at Module.load (module.js:355:32)
2015-02-05T04:59:34.692153+00:00 heroku[web.1]: Process exited with status 1
2015-02-05T04:59:34.707517+00:00 heroku[web.1]: State changed from starting to crashed
2015-02-06T01:00:22.267010+00:00 heroku[web.1]: State changed from crashed to starting
2015-02-06T01:00:25.829599+00:00 heroku[web.1]: Starting process with command `node --harmony index.js`
2015-02-06T01:00:27.584290+00:00 app[web.1]:           ^
2015-02-06T01:00:27.584293+00:00 app[web.1]:     at Function.Module._resolveFilename 
2015-02-06T16:47:37.240631+00:00 heroku[web.1]: Process exited with status 1
2015-02-06T16:47:37.255797+00:00 heroku[web.1]: State changed from starting to crashed
```

**Comment by icodeforlove** [comment]
yeah that seems like a typo :/, try making it `cubby`
